# Site settings
title: Takashi Kawamura
description: PhD Student, Research Center for Advanced Science and Technology (RCAST), The University of Tokyo
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://takashi-kawamura.github.io" # the base hostname & protocol for your site

author:
  name: "Takashi Kawamura"
  email: "tkawamura@atmos.rcast.u-tokyo.ac.jp"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Build settings
markdown: kramdown
highlighter: rouge

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Include
include: ["_pages"]

# Language
locale: en-US

atom_feed:
  hide: true
